/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package me.internalizable.musically.panels;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Random;
import java.util.concurrent.ThreadLocalRandom;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import me.internalizable.musically.CoreFrame;
import me.internalizable.musically.persistence.Song;
import me.internalizable.musically.utilities.AudioPlayer;
import org.apache.commons.io.FileUtils;

/**
 *
 * @author Internalizable
 */
public class SongPanel extends javax.swing.JPanel {

    private String latestPreviewURL = null;
    private Thread preview;
    
    /**
     * Creates new form SplashPanel
     */
    public SongPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        artwork = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        artist = new javax.swing.JLabel();
        album = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        duration = new javax.swing.JLabel();
        backIcon = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel10.setText("jLabel10");

        setBackground(new java.awt.Color(0, 0, 0));

        artwork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/200x200bb.jpeg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Listen");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(190, 155, 100));
        jLabel4.setText("History");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(190, 155, 100));
        jLabel5.setText("Profile");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(190, 155, 100));
        jLabel6.setText("Sign out");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        name.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Song Name");

        artist.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        artist.setForeground(new java.awt.Color(255, 255, 255));
        artist.setText("Artist");

        album.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        album.setForeground(new java.awt.Color(255, 255, 255));
        album.setText("Album");

        year.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        year.setForeground(new java.awt.Color(255, 255, 255));
        year.setText("Year");

        duration.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        duration.setForeground(new java.awt.Color(255, 255, 255));
        duration.setText("Duration: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(artist)
                    .addComponent(name)
                    .addComponent(album)
                    .addComponent(year)
                    .addComponent(duration))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(name)
                .addGap(18, 18, 18)
                .addComponent(artist)
                .addGap(19, 19, 19)
                .addComponent(album)
                .addGap(18, 18, 18)
                .addComponent(year)
                .addGap(18, 18, 18)
                .addComponent(duration)
                .addContainerGap())
        );

        backIcon.setForeground(new java.awt.Color(255, 255, 255));
        backIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Path 74@1X.png"))); // NOI18N

        back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Eclipse-1s-81px.gif"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(190, 155, 100));
        jLabel7.setText("Loading song preview...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(back)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(artwork, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(backIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addComponent(artwork, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel7)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        CoreFrame.getInstance().changeView("home");
        preview.stop();
    }//GEN-LAST:event_backMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       
        int reply = JOptionPane.showConfirmDialog(this, "Are you sure you want to sign out?", "Sign Out?", JOptionPane.YES_NO_OPTION);
        
        if (reply == JOptionPane.YES_OPTION) {
            CoreFrame.getInstance().changeView("login");
            preview.stop();
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        CoreFrame.getInstance().changeView("history");
        preview.stop();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        CoreFrame.getInstance().changeView("profile");
        preview.stop();
    }//GEN-LAST:event_jLabel5MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel album;
    private javax.swing.JLabel artist;
    private javax.swing.JLabel artwork;
    private javax.swing.JLabel back;
    private javax.swing.JLabel backIcon;
    private javax.swing.JLabel duration;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel year;
    // End of variables declaration//GEN-END:variables

    public void setActiveSong(Song song) {
        name.setText(song.getName());
        album.setText(song.getAlbum());
        artist.setText(song.getArtist());
        year.setText(song.getReleaseDate());
        duration.setText(song.getDuration());
        
        ImageIcon imageIcon = me.internalizable.musically.utilities.FileUtils.getImage(song, 200, 200);
        
        if(imageIcon != null)
            artwork.setIcon(imageIcon);
        
        latestPreviewURL = song.getPreviewLink();
    }
    
    public void playPreviewIfExists() {
        
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Eclipse-1s-81px.gif")));
        
        if(latestPreviewURL == null) {
            jLabel3.setVisible(false);
            jLabel7.setVisible(false);
            return;
        }
            
        
        preview = new Thread(() -> {
            try {
                
                jLabel3.setVisible(true);
                jLabel7.setVisible(true);
                    
                File downloadedFile = new File("playback");
                
                FileUtils.copyURLToFile(
                        new URL(latestPreviewURL),
                        downloadedFile);
                
                jLabel7.setVisible(false);
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/output-onlinegiftools.gif")));
                AudioPlayer audioPlayer = new AudioPlayer(downloadedFile);
                audioPlayer.run();
                
                jLabel3.setVisible(false);
            } catch (MalformedURLException ex) {
                Logger.getLogger(SongPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(SongPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        
        preview.start();
    }
}
